# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField()),
                ('events_list', models.CharField(choices=[(b'FR50', b'50m Freestyle'), (b'FR100', b'100m Freestyle'), (b'FR200', b'200m Freestyle'), (b'BF50', b'50m Butterfly'), (b'FR100', b'100m Butterfly'), (b'FR200', b'200m Butterfly'), (b'BR50', b'50m Brest Stroke'), (b'BR100', b'100m Brest Stroke'), (b'BR200', b'200m Brest Stroke'), (b'BA50', b'50m Back Stroke'), (b'BA100', b'100m Back Stroke'), (b'BA200', b'200m Back Stroke'), (b'IM100', b'Individual Medley 100m'), (b'IM200', b'Individual Medley 200m')], max_length=20)),
            ],
        ),
    ]
