# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='team_manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sportsman.TeamManager'),
            preserve_default=False,
        ),
    ]
