# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0004_auto_20170203_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammanager',
            name='manager_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
