# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0005_teammanager_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=0, max_length=6),
            preserve_default=False,
        ),
    ]
