# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0007_auto_20170206_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_approved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
