# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:38
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0008_participant_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='events_list',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'50m Freestyle', b'50m Freestyle'), (b'100m Freestyle', b'100m Freestyle'), (b'200m Freestyle', b'200m Freestyle'), (b'50m Butterfly', b'50m Butterfly'), (b'100m Butterfly', b'100m Butterfly'), (b'200m Butterfly', b'200m Butterfly'), (b'50m Brest Stroke', b'50m Brest Stroke'), (b'100m Brest Stroke', b'100m Brest Stroke'), (b'200m Brest Stroke', b'200m Brest Stroke'), (b'50m Back Stroke', b'50m Back Stroke'), (b'100m Back Stroke', b'100m Back Stroke'), (b'200m Back Stroke', b'200m Back Stroke'), (b'Individual Medley 100m', b'Individual Medley 100m'), (b'Individual Medley 200m', b'Individual Medley 200m')], max_length=236),
        ),
    ]
