# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0009_auto_20170206_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='birth_certificate',
            field=models.ImageField(default=b'images/not_available.png', upload_to=b'images'),
        ),
    ]
