# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0010_participant_birth_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammanager',
            name='id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='birth_certificate',
            field=models.ImageField(default=b'images/not_available.jpg', upload_to=b'images'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='teammanager',
            name='mobile_phone',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(b'^\\d{1,10}$')]),
        ),
    ]
