# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0011_auto_20170208_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammanager',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammanager',
            name='mobile_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(b'^\\d{1,10}$')]),
        ),
    ]
